# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afc5788fe0e1079fe6958595d4f0d155a65561b9f64dc1f01b2fe12fcebc7f88bbc05e0f5f06a8cfc109cdca146ca5d18cb317565f4ae3f5c0d5a596612d5a8f

test:
  secret_key_base: 90363dd1499a36f3057fbd275f4689fe18c4a8566cc8264d1ff24fe802d44bbe35ba6b15cc3a86ca4d13fc9b889bb427d2c6f4a13f0e6f5c8c056abef3d7c269

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
